/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.login_form;

import java.awt.Image;
import java.sql.Blob;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JhayJTheGosu
 */
public class viewform extends javax.swing.JFrame {
    
   String studentNumber, lastName, firstName, middleName, address, birthDate, department, course;
   ImageIcon picture;
    public void getInfo(String studentNumber, String lastName, String firstName, String middleName, String address, String birthDate, String department, String course, ImageIcon picture){
      this.studentNumber = studentNumber;
      this.lastName = lastName;
      this.firstName = firstName;
      this.middleName = middleName;
      this.address = address;
      this.birthDate = birthDate;
      this.department = department;
      this.course = course;
      this.picture = picture;
      System.out.println("fg");
   }
    /**
     * Creates new form viewform
     */
    
    public viewform() {
        initComponents();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        vstudentNumber = new javax.swing.JLabel();
        vfirstName = new javax.swing.JLabel();
        vlastName = new javax.swing.JLabel();
        vaddress = new javax.swing.JLabel();
        vmiddleName = new javax.swing.JLabel();
        vbirthDate = new javax.swing.JLabel();
        vdepartment = new javax.swing.JLabel();
        vcourse = new javax.swing.JLabel();
        vpicture = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(134, 167, 137));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel1.setText("Student Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        jPanel2.setBackground(new java.awt.Color(53, 48, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vstudentNumber.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        vstudentNumber.setForeground(new java.awt.Color(250, 240, 230));
        vstudentNumber.setText("s");
        jPanel2.add(vstudentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 69, -1));

        vfirstName.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        vfirstName.setForeground(new java.awt.Color(250, 240, 230));
        vfirstName.setText("f");
        jPanel2.add(vfirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 69, -1));

        vlastName.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        vlastName.setForeground(new java.awt.Color(250, 240, 230));
        vlastName.setText("l");
        jPanel2.add(vlastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 69, -1));

        vaddress.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        vaddress.setForeground(new java.awt.Color(250, 240, 230));
        vaddress.setText("b");
        jPanel2.add(vaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 69, -1));

        vmiddleName.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        vmiddleName.setForeground(new java.awt.Color(250, 240, 230));
        vmiddleName.setText("m");
        jPanel2.add(vmiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 69, -1));

        vbirthDate.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        vbirthDate.setForeground(new java.awt.Color(250, 240, 230));
        vbirthDate.setText("a");
        jPanel2.add(vbirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 69, -1));

        vdepartment.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        vdepartment.setForeground(new java.awt.Color(250, 240, 230));
        vdepartment.setText("d");
        jPanel2.add(vdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 250, -1));

        vcourse.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        vcourse.setForeground(new java.awt.Color(250, 240, 230));
        vcourse.setText("c");
        jPanel2.add(vcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 250, -1));

        vpicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(vpicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 140, 120));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 240, 230));
        jLabel3.setText("Middle name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 240, 230));
        jLabel4.setText("Student No. :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 240, 230));
        jLabel5.setText("Last name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 240, 230));
        jLabel6.setText("Birthdate");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(250, 240, 230));
        jLabel7.setText("Address");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 240, 230));
        jLabel8.setText("Course");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 240, 230));
        jLabel9.setText("First name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(250, 240, 230));
        jLabel10.setText("Department");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        btn_exit.setBackground(new java.awt.Color(0, 150, 255));
        btn_exit.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(250, 240, 230));
        btn_exit.setText("Exit");
        btn_exit.setBorder(null);
        btn_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.setPreferredSize(new java.awt.Dimension(70, 30));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 70, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            getInfo( studentNumber, lastName, firstName, middleName, address, birthDate, department, course, picture);
            vstudentNumber.setText(studentNumber);
            vlastName.setText(lastName);
            vfirstName.setText(firstName);
            vmiddleName.setText(middleName);
            vaddress.setText(address);
            vbirthDate.setText(birthDate);
            vdepartment.setText(department);
            vcourse.setText(course);
            int labelWidth = vpicture.getWidth();
            int labelHeight = vpicture.getHeight();
            
            Image scaledImage = picture.getImage().getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);
            vpicture.setIcon(scaledIcon);
            
    }//GEN-LAST:event_formWindowActivated

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
       dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel vaddress;
    private javax.swing.JLabel vbirthDate;
    private javax.swing.JLabel vcourse;
    private javax.swing.JLabel vdepartment;
    private javax.swing.JLabel vfirstName;
    private javax.swing.JLabel vlastName;
    private javax.swing.JLabel vmiddleName;
    private javax.swing.JLabel vpicture;
    private javax.swing.JLabel vstudentNumber;
    // End of variables declaration//GEN-END:variables
}
